---
title: "Hello Winnipeg & Winnipeg Data Nerds"
authors: ["jdallmann"]
menu: 
    main: 
        name: Posts
    sidebar:
        name: Posts
date: 2019-12-31
weight: -200
categories: ["housekeeping"]
tags: ["about", "open data", "kickoff"]
---



# Hi Winnipeg, Manitoba

I'm kicking off 2020 with a data blogging experiment, centered on exploring openly available Winnipeg data. 

Why?

First, as a early career data scientist, I've been spending a bunch of time working through data on Winnipeg and other Canadian cities. More of it turned out to be interesting than I initially expected, so I thought I'd start sharing some of it here. Plus, a blog seems like a good venue to try out (and record, for my future self) some new analysis techniques. If other data nerds might benefit, all the better.

Second, I'm kind of attached to this city. I've left it for larger (and obviously warmer) cities before, but it has a way of  [charming you into returning](https://www.youtube.com/watch?v=8L4cttwNaDs)...

It is the primary location of maybe the [least boring saga in Canadian history](https://en.wikipedia.org/wiki/Red_River_Rebellion), super [bio-diverse](https://www.naturemanitoba.ca/), seasonally diverse (perhaps for the worse), and often [hit](https://shawglobalnews.files.wordpress.com/2018/03/tracy-eyolfson-winnipeg-new.jpg) by [unexpected beauty](https://www.travelmanitoba.com/things-to-do/all-seasons/aurora-borealis-northern-lights/) that, I'd argue, rivals that of the "pretty provinces". Plus, [cultural references](https://www.youtube.com/watch?v=8L4cttwNaDs) to our ["frigid Tundra"](https://www.nationalgeographic.com/science/2019/11/its-cool-to-be-cold-confessions-of-frigid-weather-fanatics/), really give it that international allure.


Lastly, it would be great to contribute to a data-based conversation about our city. As the place we live and pay to maintain as tax-payers, pretty much everyone has a view on it. Encouraging double-checking (or single-checking) those views against data would be a plus. So, let's engage in some baseless speculation together (a favorite past-time), and self-correct against actual data (another favourite past-time). Maybe we'll get somewhere together.

&nbsp;
&nbsp;
&nbsp;

Talk soon Winnipeg Data nerds!


<small> All of the views expressed on this blog are my own opinions, all data is openly available, and all analyses coded using reproducible research methods posted to Github in the link below. </small> 